name: 'Bug report for v4.0.0-beta.x'
description: 'This form is for reporting bugs in the beta version of the plugin. If you are using an older version, please choose "Bug report" instead.'
title: '[BETA]: '
labels: ['pdk']

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Note: ⚠️**

        This form is for reporting bugs in the beta version of the plugin (>= v4.0.0-beta.x). If you are using an older version, please use the [regular bug report form](https://github.com/myparcelnl/prestashop/issues/new?labels=bug&template=BUG-REPORT.yml) instead.

  - type: checkboxes
    id: version-check
    attributes:
      label: 'Version check'
      options:
        - label: 'My version of the plugin is v4.0.0-beta.0 or above.'
          required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form! We will respond as fast as we can. Don't forget to check
        whether your issue might be a [duplicate of an existing one](https://github.com/myparcelnl/prestashop/issues) before submitting.

  - type: input
    id: myparcel-version
    attributes:
      label: 'MyParcelNL version'
      description: 'Which version of the MyParcelNL beta module are you using?'
      placeholder: 'v4.0.0-beta.3'
    validations:
      required: true
  - type: input
    id: ps-version
    attributes:
      label: 'PrestaShop version'
      description: 'Which PrestaShop version are you using?'
      placeholder: '8.0.0'
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      placeholder: '8.1'
      label: 'PHP version'
      description: 'Which PHP version are you using?'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'What went wrong?'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 'Reproduction steps'
      description: 'Steps to reproduce this behavior.'
      value: |
        1. Navigate to ...
        2. Click on ...
        3. See ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 'Relevant log output'
      description: 'Copy and paste any relevant log output here. Proper formatting will be applied automatically.'
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: |
        Add any other context or screenshots about the bug here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
