name: '⚙️ On push'

on:
  push:
    branches:
      - alpha
      - beta

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: myparcelnl/actions/pdk-prerelease-push@v4
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          image: ${{ steps.build.outputs.image }}
          source-files: |
            src/**/*
            config/**/*
            controllers/**/*
            upgrade/**/*
            myparcelnl.php
            scoper.inc.php

  rebase-prs:
    uses: ./.github/workflows/rebase-prs.yml
    secrets: inherit
