name: '🧪 Run tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref to run on'
        type: string
        required: false

jobs:
  test-frontend:
    runs-on: ubuntu-22.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: coverage-cache
        with:
          path: coverage
          key: coverage-${{ hashFiles('**/package.json', '**/yarn.lock', 'views/**/*') }}

      - uses: myparcelnl/actions/pdk-setup-frontend@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'

      - uses: myparcelnl/actions/pdk-upgrade@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          report: 'false'
          no-check: true
          no-commit: true

      - name: 'Run frontend tests'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        uses: myparcelnl/actions/nx-run-many@v4
        with:
          target: 'test:coverage'
          args: '--parallel=1'

      - name: 'Move coverage files'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          yarn workspaces foreach -Apv --exclude . exec \
            bash -c 'if [ -f coverage/clover.xml ]; then mv coverage/clover.xml coverage/$(basename $(pwd)).xml; fi'

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,frontend,admin
          files: views/backend/**/coverage/*.xml

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,frontend,checkout
          files: views/frontend/**/coverage/*.xml

  test-backend:
    runs-on: ubuntu-22.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: coverage-cache
        with:
          path: coverage
          key: coverage-${{ hashFiles('**/composer.json', '**/composer.lock', 'src/**/*', 'tests/**/*') }}

      - uses: myparcelnl/actions/pdk-setup@v4
        id: setup
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - uses: myparcelnl/actions/pdk-upgrade@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          report: 'false'
          no-check: true
          no-commit: true
          image: ${{ steps.setup.outputs.image }}

      - uses: myparcelnl/actions/composer-pest@v4
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        with:
          image: ${{ steps.setup.outputs.image }}

      - name: 'Move coverage file'
        if: steps.coverage-cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          mkdir -p coverage
          docker cp $(docker ps -alq):/app/clover.xml coverage/backend.xml

          # Strip the /app/ prefix from the coverage paths before uploading.
          sed -i 's/\/app\///g' coverage/backend.xml

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,backend
          files: coverage/*.xml
