name: '🧪 Run tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Ref to run on'
        type: string
        required: false

jobs:
  test-frontend:
    runs-on: ubuntu-22.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: cache
        with:
          path: coverage
          key: coverage-frontend-${{ hashFiles('**/package.json', '**/yarn.lock', 'views/**/*') }}

      - uses: myparcelnl/actions/pdk-setup-upgrade@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          mode: 'frontend'

      - name: 'Run frontend tests'
        if: steps.cache.outputs.cache-hit != 'true'
        uses: myparcelnl/actions/nx-run-many@v4
        with:
          target: 'test:coverage'
          args: '--parallel=1'

      - name: 'Move coverage files'
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          # Create the coverage directory in case it doesn't exist
          mkdir -p coverage

          # Copy the coverage files to the coverage folder, named after the project.
          yarn workspaces foreach -Apv --exclude . exec \
            bash -c 'if [ -f coverage/clover.xml ]; then cp -f coverage/clover.xml ../../../../coverage/$(basename $PWD).xml; fi'

          # Strip the /app/ prefix from the coverage paths before uploading.
          find coverage -type f -name '*.xml' -exec sed -i 's/\/app\///g' {} \;

      - uses: myparcelnl/actions/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,frontend
          files: coverage/**/*.xml

  test-backend:
    runs-on: ubuntu-22.04
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: 'Cache coverage'
        uses: actions/cache@v4
        id: cache
        with:
          path: clover.xml
          key: coverage-backend-${{ hashFiles('**/composer.json', '**/composer.lock', 'src/**/*', 'tests/**/*') }}

      - uses: myparcelnl/actions/pdk-setup-upgrade@v4
        if: steps.cache.outputs.cache-hit != 'true'
        id: setup
        with:
          app-id: ${{ secrets.MYPARCEL_APP_ID }}
          private-key: ${{ secrets.MYPARCEL_APP_PRIVATE_KEY }}
          php-version: ${{ vars.PHP_VERSION }}
          mode: 'backend'

      - uses: myparcelnl/actions/composer-pest@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          image: ${{ steps.setup.outputs.image }}

      - name: 'Move coverage file'
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        #language=bash
        run: |
          # Strip the /app/ prefix from the coverage paths before uploading.
          sed -i 's/\/app\///g' clover.xml

      - uses: myparcelnl/actions/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unit,backend
          files: clover.xml
